language: objective-c

branches:
 only:
 - master

xcode_project: Rethink.xcodeproj
xcode_scheme: Rethink
osx_image: xcode8

before_install:
 - brew install rethinkdb

before_script:
 - rethinkdb --daemon
 - sleep 10

script:
- swift package generate-xcodeproj
- xcodebuild clean build test -project Rethink.xcodeproj -scheme Rethink CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""

after_script:
 - killall rethinkdb
